config/routes.rb
Instagram::Application.routes.draw do

  root :to => "myanmar#index"

  get "about/about"
  get "myanmar/index"
  get "myanmar/yangon"
  get "myanmar/chaungthar"
  get "myanmar/mandalay"
  get "myanmar/ngwesaung"
  get "myanmar/pathein"
  get "myanmar/taunggyi"
  get "about/me"

  match '/about', :to => 'about#about'
  match '/yangon', :to => 'myanmar#yangon'
  match '/mandalay', :to => 'myanmar#mandalay'
  match '/taunggyi', :to => 'myanmar#taunggyi'
  match '/pathein', :to => 'myanmar#pathein'
  match '/ngwesaung', :to => 'myanmar#ngwesaung'
  match '/chaungthar', :to => 'myanmar#chaungthar'
  match '/home', :to => 'myanmar#index'
  match '/Me', :to => 'about#me', as: :me

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
  def me
  	@instagram = Instagram.user_recent_media(205063538, :count => 33)
    @title = "Phyo Min Htun"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/myanmar_controller.rb
class MyanmarController < ApplicationController
  def yangon
    @instagram = Instagram.media_search("16.8000","96.1500", {:count => 33})
    @title = "Yangon"
  end

  def chaungthar
    @instagram = Instagram.media_search("16.955770400000000000","94.447562399999920000", {:count => 33})
    @title = "Chaung Thar"
  end

  def mandalay
    @instagram = Instagram.media_search("21.9750","96.0833", {:count => 33})
    @title = "Mandalay"
  end

  def ngwesaung
    @instagram = Instagram.media_search("16.8583","94.3917", {:count => 33})
    @title = "Ngwe Saung"
  end

  def pathein
    @instagram = Instagram.media_search("16.7742","94.7317", {:count => 33})
    @title = "Pathein"
  end

  def taunggyi
    @instagram = Instagram.media_search("20.7836","97.0354", {:count => 33})
    @title = "Taung Gyi"
  end

  def index
    @instagram = Instagram.tag_recent_media("instamyanmar", {:count => 33})
    @title = "Home"
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	# Return a title on per-page basis.
	def title
		base_title = "#InstaMyanmar"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/myanmar_helper.rb
module MyanmarHelper
end

app/views/about/about.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<div class="jumbotron">
	<h1>About Us</h1>
        <p class="lead" style="font-size: 20px">Created By <br>
        	<i><b><a href="https://twitter.com/OhDawood" target="_blank">Phyo Min Htun</a></b></i> <br>(Front-End Developer)</p><br>
    <h1>How To ?</h1>
    <p class="lead" style="font-size: 17px">This app show you a 30 recent picture of Myanmar.<br><br>
       Just click on your preferred city and have a look.<br><br>

       Why do you have access to my pictures :o ?<br><br>

       Because you choose to make your Instagram stream public AND because you Geotagged your pictures.<br><br>

       How do I stop this?<br><br>

       Set your stream to "private" in Instagram. And/Or don't geotag your pictures. That way it won't show up on our website. (It will still be public and other services could still access it, but we don't access it.)<br><br>

       How can I be a part of it?<br><br>

       Install the free Instagram App on your phone.<br>
       Take a picture with Instagram in one of the cities mentioned above.<br>
       That's it. Your image just got published on InstaMyanmar<br></p>
</div>

app/views/about/me.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "screen" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="body">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

  </script>
	<div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= home_path %>">#InstaMyanmar</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="<%= yangon_path %>">Yangon</a></li>
            <li><a href="<%= mandalay_path %>">Mandalay</a></li>
            <li><a href="<%= chaungthar_path %>">Chaung Thar</a></li>
            <li><a href="<%= ngwesaung_path %>">Ngwe Saung</a></li>
            <li><a href="<%= taunggyi_path %>">Taung Gyi</a></li>
            <li><a href="<%= pathein_path %>">Pathein</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->
<div class="container insta_application_body" id="insta_application_body">
	<%= yield %>
</div>

<footer class="container">
        <p class="para">&copy; <b>PhyoLabs 2014</b><a href="mailto:phyolabs@gmail.com" class="about_contact">Contact Us</a><a href="<%= about_path %>" class="about_contact">About Us</a></p>
</footer>
</body>
</html>

app/views/myanmar/chaungthar.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>

app/views/myanmar/index.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>

app/views/myanmar/mandalay.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>

app/views/myanmar/ngwesaung.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>

app/views/myanmar/pathein.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>

app/views/myanmar/taunggyi.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>

app/views/myanmar/yangon.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45491079-2', 'instamyanmar.herokuapp.com');
  ga('send', 'pageview');

</script>
<% @instagram.each do |instagram| %>
	<ul class="ic-appul">
		<div id="ic-app">
			<li class="ic-appuseravi"><img src="<%= instagram.user.profile_picture %>"></li>
			<h3><i><%= instagram.user.username %></i></h3>
			<a href="<%= instagram.link %>" target="_blank"><img src="<%= instagram.images.standard_resolution.url %>" class="ic-images"></a><br><br>
			<p class="p"><a href="<%= instagram.images.standard_resolution.url %>" class="ic-download" download="InstaCity.jpg" target="_blank">Download</a></p>
		</div>
	</ul>
<% end %>